use std::libc::{c_char, c_void};

pub static _VI_ERROR: i32 = 0x80000000;
pub static VI_SUCCESS: i32 = 0;
pub static VI_NULL: i32 = 0;
pub static VI_TRUE: i32 = 1;
pub static VI_FALSE: i32 = 0;
pub static VI_SPEC_VERSION: u32 = 0x00500100;

struct ViUInt64(u64);
struct ViInt64(i64);
struct ViUInt32(u32);
struct ViInt32(i32);
struct ViUInt16(u16);
struct ViInt16(i16);
struct ViUInt8(u8);
struct ViInt8(i8);
struct ViChar(c_char);
struct ViByte(u8);
struct ViAddr(~c_void);
struct ViReal32(f32);
struct ViReal64(f64);
struct ViBuf(u8);
struct ViString(~c_char);
struct ViRsrc(~c_char);
struct ViBoolean(u16);
struct ViStatus(i32);
struct ViVersion(u32);
struct ViObject(u32);
struct ViSession(u32);
struct ViAttr(u32);
struct ViEvent(u32);
struct ViFindList(u32);
struct ViBusAddress(uint);
struct ViBusSize(uint);
struct ViAttrState(uint);
struct ViBusAddress64(u64);
struct ViEventType(u32);
struct ViKeyId(~c_char);
struct ViJobId(u32);
struct ViAccessMode(u32);
struct ViEventFilter(u32);
// struct ViVAList(????);
